version: '3.8'

services:
  BigDataDocker:
    image: mysql:8.0
    container_name: BigDataDocker
    environment:
      MYSQL_ROOT_PASSWORD: hola1234
    ports:
      - "4535:3306"
      - "4536:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: